{"name": "test_sea_file_login[seafile@admin.com-admin666-400-Unable to login with provided credentials]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 400 == (400 + 1)\n +  where 400 = <Response [400]>.status_code", "trace": "username = 'seafile@admin.com', password = 'admin666', code = '400'\nmsg = 'Unable to login with provided credentials'\n\n    @allure.step(\"接口1（登录接口）的用例\")\n    @pytest.mark.parametrize([\"username\", \"password\", \"code\", \"msg\"], get_csv_data(\"./data/01seafile_login.csv\"))\n    def test_sea_file_login(username, password, code, msg):\n        allure.attach(\"登录\", \"步骤01\")\n        response = sea_file_login(username, password)\n        allure.attach(\"将输入的csv里面的code类型从str转化成int\", \"步骤02\")\n        a = eval(code)\n        allure.attach(\"断言状态码是否符合预期\", \"步骤03\")\n>       assert response.status_code == a+1\nE       assert 400 == (400 + 1)\nE        +  where 400 = <Response [400]>.status_code\n\ntest_case\\test_07.py:16: AssertionError"}, "steps": [{"name": "接口1（登录接口）的用例", "status": "failed", "statusDetails": {"message": "AssertionError: assert 400 == (400 + 1)\n +  where 400 = <Response [400]>.status_code\n", "trace": "  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"D:\\testgit\\Interface-Automation-Basics\\test_case\\test_07.py\", line 16, in test_sea_file_login\n    assert response.status_code == a+1\n"}, "attachments": [{"name": "步骤01", "source": "f937f556-c4e3-45aa-b273-4af6ab917ec5-attachment.attach"}, {"name": "步骤02", "source": "e2d35b34-3797-4a06-b054-ff45297c20f8-attachment.attach"}, {"name": "步骤03", "source": "e6776357-5167-4378-882a-e1a71e68ef9e-attachment.attach"}], "parameters": [{"name": "username", "value": "'seafile@admin.com'"}, {"name": "password", "value": "'admin666'"}, {"name": "code", "value": "'400'"}, {"name": "msg", "value": "'Unable to login with provided credentials'"}], "start": 1749804840922, "stop": 1749804840939}], "attachments": [{"name": "log", "source": "e372c183-2f74-4677-8b64-36c35d42332d-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'seafile@admin.com'"}, {"name": "password", "value": "'admin666'"}, {"name": "code", "value": "'400'"}, {"name": "msg", "value": "'Unable to login with provided credentials'"}], "start": 1749804840922, "stop": 1749804840939, "uuid": "d045df50-ccaf-443e-9bf4-8ec84886c267", "historyId": "e7bc4e0d840b12f94864f4016fc54c55", "testCaseId": "de8b2b1b22432fbc4ae3a40e7eff706d", "fullName": "test_case.test_07#test_sea_file_login", "labels": [{"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_07"}, {"name": "host", "value": "stu001243"}, {"name": "thread", "value": "17100-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_07"}]}