{"name": "test_sea_file_login[seafile@admin.com666-admin-400-Unable to login with provided credentials]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 400 == (400 + 1)\n +  where 400 = <Response [400]>.status_code", "trace": "username = 'seafile@admin.com666', password = 'admin', code = '400'\nmsg = 'Unable to login with provided credentials'\n\n    @allure.step(\"接口1（登录接口）的用例\")\n    @pytest.mark.parametrize([\"username\", \"password\", \"code\", \"msg\"], get_csv_data(\"./data/01seafile_login.csv\"))\n    def test_sea_file_login(username, password, code, msg):\n        allure.attach(\"登录\", \"步骤01\")\n        response = sea_file_login(username, password)\n        allure.attach(\"将输入的csv里面的code类型从str转化成int\", \"步骤02\")\n        a = eval(code)\n        allure.attach(\"断言状态码是否符合预期\", \"步骤03\")\n>       assert response.status_code == a+1\nE       assert 400 == (400 + 1)\nE        +  where 400 = <Response [400]>.status_code\n\ntest_case\\test_07.py:16: AssertionError"}, "steps": [{"name": "接口1（登录接口）的用例", "status": "failed", "statusDetails": {"message": "AssertionError: assert 400 == (400 + 1)\n +  where 400 = <Response [400]>.status_code\n", "trace": "  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"D:\\testgit\\Interface-Automation-Basics\\test_case\\test_07.py\", line 16, in test_sea_file_login\n    assert response.status_code == a+1\n"}, "attachments": [{"name": "步骤01", "source": "3e22848b-87ba-4af7-9529-8ee8419c11be-attachment.attach"}, {"name": "步骤02", "source": "9794f46f-2b72-4afd-b8f1-12cbbf303dec-attachment.attach"}, {"name": "步骤03", "source": "0a972022-0bda-4dfb-a6e2-f19db140b1cf-attachment.attach"}], "parameters": [{"name": "username", "value": "'seafile@admin.com666'"}, {"name": "password", "value": "'admin'"}, {"name": "code", "value": "'400'"}, {"name": "msg", "value": "'Unable to login with provided credentials'"}], "start": 1749804840905, "stop": 1749804840915}], "attachments": [{"name": "log", "source": "19bf9494-39ae-4d4d-ba59-56178f0d46e8-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'seafile@admin.com666'"}, {"name": "password", "value": "'admin'"}, {"name": "code", "value": "'400'"}, {"name": "msg", "value": "'Unable to login with provided credentials'"}], "start": 1749804840905, "stop": 1749804840916, "uuid": "31fd8313-31d2-421f-88f3-37d39b833749", "historyId": "3ed3ce442befc124eb68e87db4839d0e", "testCaseId": "de8b2b1b22432fbc4ae3a40e7eff706d", "fullName": "test_case.test_07#test_sea_file_login", "labels": [{"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_07"}, {"name": "host", "value": "stu001243"}, {"name": "thread", "value": "17100-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_07"}]}