WARNING  pytest_result_log:plugin.py:122 Start: testcase/test07.py::test_sea_file_1_5[8ac00e05a7652b31598a56d764bd5b5f7c45a6ef-59bbf7e9-2748-41ce-a9a9-1e8d44360484-111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111255-200-success]
WARNING  pytest_result_log:plugin.py:128 End: testcase/test07.py::test_sea_file_1_5[8ac00e05a7652b31598a56d764bd5b5f7c45a6ef-59bbf7e9-2748-41ce-a9a9-1e8d44360484-111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111255-200-success]